modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="technologies_of_another_world"
version="1.0.0"
displayName="technologies of another world"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="krbs312, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.technologies_of_another_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.technologies_of_another_world]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technologies_of_another_world]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technologies_of_another_world]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration